xcodebuild_arguments:
  - -scheme
  - DNS
module: DNS
author: Bouke Haarsma
author_url: https://twitter.com/BoukeHaarsma
output: ../DNS-Docs/master
theme: fullwidth
clean: true
github_url: https://github.com/Bouke/DNS
dash_url: http://boukehaarsma.nl/DNS/DNS.xml
