language: generic
sudo: required
script:
  - swift test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then carthage build --no-skip-current ; fi
matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: linux
      dist: trusty
      install:
        - wget https://swift.org/builds/swift-4.0-release/ubuntu1404/swift-4.0-RELEASE/swift-4.0-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-4.0-RELEASE-ubuntu14.04.tar.gz
        - export PATH=`pwd`/swift-4.0-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
