language: generic
sudo: required
script: swift test
matrix:
  include:
    - os: osx
      osx_image: xcode11
    - os: linux
      dist: trusty
      install:
        - wget https://swift.org/builds/swift-5.1.3-release/ubuntu1404/swift-5.1.3-RELEASE/swift-5.1.3-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-5.1.3-RELEASE-ubuntu14.04.tar.gz
        - export PATH=`pwd`/swift-5.1.3-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
    - name: Code Quality Checks
      os: osx
      osx_image: xcode11
      install:
        - brew update
        - brew upgrade swiftlint || true
      addons:
        sonarcloud:
          organization: bouke-github
      script:
        - swiftlint --strict
        - sonar-scanner
